#!/bin/sh
DIRS="Bootloader/u-boot-novasom-2015.04 Kernel/linux-imx_3.10.53_1.1.0_ga Kernel/linux-imx_4.1.15_1.2.0_ga Doc Utils Qt/NOVAembed/NOVAembed CodeBlocks Xcompiler"
REPOCOUNT=`echo "$DIRS" | awk '{print NF}'`

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

COUNTMODS=0
COUNTRECV=0
INCREMENT=1

gitloop()
{
gitbin="git -C $1"

# Fetches from all the remotes, although --all can be replaced with origin
$gitbin fetch origin
if [ $($gitbin rev-parse HEAD)>/dev/null 2>&1 != $($gitbin rev-parse @{u})>/dev/null 2>&1 ]; then
	cd $1
	COUNTMODS=`expr $COUNTMODS + $INCREMENT`;
	#$gitbin rebase @{u} --preserve-merges
	echo "  ${RED}Updates in ${1}${NC}"
	echo -n "  Do you want to update ? [Y/n] "
	read VAR
	if [ "${VAR}" = "Y" ]; then
		if [ "${1}" = "/Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed" ]; then
			mv /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed/NOVAembed.pro.user /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed/NOVAembed.pro.userOLD
		fi
		git pull origin master
		COUNTRECV=`expr $COUNTRECV + $INCREMENT`;
		echo $1
		if [ "${1}" = "/Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed" ]; then
			HERE=`pwd`
			cd /Devel/NOVAsom_SDK/Qt/NOVAembed/build-NOVAembed-Desktop-Debug
			make distclean
			/usr/lib/x86_64-linux-gnu/qt5/bin/qmake /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed/NOVAembed.pro -r -spec linux-g++-64 CONFIG+=debug
			make
			cd /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed/NOVAembed_P_Parser
			gcc -Wall -g  -c /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed/NOVAembed_P_Parser/src/dts_gen.c -o obj/Debug/src/dts_gen.o
			gcc -Wall -g  -c /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed/NOVAembed_P_Parser/src/iomux.c -o obj/Debug/src/iomux.o
			gcc -Wall -g  -c /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed/NOVAembed_P_Parser/src/main.c -o obj/Debug/src/main.o
			g++  -o bin/Debug/NOVAembed_P_Parser obj/Debug/src/dts_gen.o obj/Debug/src/iomux.o obj/Debug/src/main.o 
			cd ${HERE} 
		fi
		echo "${GREEN}SYNC OK${NC} : ${1}"
	else
		echo "${RED}Update skipped${NC}"
	fi
else
	echo "${GREEN}SYNC OK${NC} : ${1}"
fi
}

echo ""
echo "***************************************"
echo "**  Check for remote modified files  **"
echo "***************************************"
echo ""

for i in ${DIRS}; do
	gitloop /Devel/NOVAsom_SDK/$i
done
echo ""
echo "Finished. Found ${RED}${COUNTMODS}${NC} modification(s) , ${RED}${COUNTRECV}${NC} file(s) received from remote to ${GREEN}${REPOCOUNT}${NC} local repos"
echo ""

exit ${COUNTRECV}

