#!/bin/sh
DIRS="Bootloader/u-boot-novasom-2015.04 Kernel/linux-imx_3.10.53_1.1.0_ga Kernel/linux-imx_4.1.15_1.2.0_ga Doc Utils Qt/NOVAembed/NOVAembed"

for i in ${DIRS}; do
        cd /Devel/NOVAsom_SDK/$i
        LOCALBASE=`basename $i`
	UPSTREAM=${1:-'@{u}'}
	LOCAL=$(git rev-parse @)	
	REMOTE=$(git rev-parse "$UPSTREAM")
	BASE=$(git merge-base @ "$UPSTREAM")
        echo -n "Check for updates in ${LOCALBASE} "

	if [ $LOCAL = $REMOTE ]; then
		echo "<-> Already at the latest version"
	elif [ $LOCAL = $BASE ]; then
		echo ""
        	echo    "  Updates in ${LOCALBASE}"
	        echo -n "  Do you want to update ? [Y/n] "
        	read VAR
	        if [ "${VAR}" = "Y" ]; then
        	        git pull origin master
		else
			echo "No update"
	        fi
	elif [ $REMOTE = $BASE ]; then
	    echo "Need to push"
	else
	    echo "Diverged"
	fi
done
