#!/bin/sh
DIRS="Bootloader/u-boot-novasom-2015.04 Kernel/linux-imx_3.10.53_1.1.0_ga Kernel/linux-imx_4.1.15_1.2.0_ga Doc Utils Qt/NOVAembed/NOVAembed CodeBlocks"

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

COUNTMODS=0
COUNTRECV=0
INCREMENT=1

echo ""
echo "***************************************"
echo "**  Check for remote modified files  **"
echo "***************************************"
echo ""

for i in ${DIRS}; do
        cd /Devel/NOVAsom_SDK/$i
        LOCALBASE=`basename $i`
	UPSTREAM=${1:-'@{u}'}
	LOCAL=$(git rev-parse @)	
	REMOTE=$(git rev-parse "$UPSTREAM")
	BASE=$(git merge-base @ "$UPSTREAM")
        echo -n "Check for updates in ${LOCALBASE} "

	if [ $LOCAL = $REMOTE ]; then
                echo -e "${GREEN}SYNC OK${NC} : ${LOCALBASE}"
	elif [ $LOCAL = $BASE ]; then
                COUNTMODS=`expr $COUNTMODS + $INCREMENT`;
                echo -e "  ${RED}Updates in ${LOCALBASE}${NC}"
                echo -n "  Do you want to update ? [Y/n] "
        	read VAR
	        if [ "${VAR}" = "Y" ]; then
        	        git pull origin master
                        COUNTRECV=`expr $COUNTRECV + $INCREMENT`;
		else
                        echo -e "${RED}Update skipped${NC}"
	        fi
	elif [ $REMOTE = $BASE ]; then
	    echo "Need to push"
	else
	    echo "Diverged"
	fi
done
