#!/bin/sh

novaembed()
{
rm -rf  /Devel/NOVAsom_SDK/Qt/NOVAembed
mkdir -p /Devel/NOVAsom_SDK/Qt/NOVAembed/build-NOVAembed-Desktop-Debug
cd /Devel/NOVAsom_SDK/Qt/NOVAembed
git clone https://github.com/NovasomIndustries/NOVAembed.git
cd /Devel/NOVAsom_SDK/Qt/NOVAembed/build-NOVAembed-Desktop-Debug
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed/NOVAembed.pro -r -spec linux-g++-64 CONFIG+=debug
make
cd /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed/NOVAembed_P_Parser
rm -rf obj bin
mkdir -p obj bin/Debug
gcc -Wall -g  -c src/dts_gen.c -o obj/dts_gen.o
gcc -Wall -g  -c src/iomux.c -o obj/iomux.o
gcc -Wall -g  -c src/main.c -o obj/main.o
g++  -o bin/Debug/NOVAembed_P_Parser obj/dts_gen.o obj/iomux.o obj/main.o
}

easypin()
{
rm -rf /Devel/NOVAsom_SDK/Qt/NOVAembed/build-P_EasyPin-Desktop-Debug /Devel/NOVAsom_SDK/Qt/NOVAembed/P_EasyPin
mkdir /Devel/NOVAsom_SDK/Qt/NOVAembed/build-P_EasyPin-Desktop-Debug
cd /Devel/NOVAsom_SDK/Qt/NOVAembed
git clone https://github.com/NovasomIndustries/P_EasyPin.git
cd /Devel/NOVAsom_SDK/Qt/NOVAembed/build-P_EasyPin-Desktop-Debug
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake /Devel/NOVAsom_SDK/Qt/NOVAembed/P_EasyPin/P_EasyPin.pro -r -spec linux-g++-64 CONFIG+=debug
make
}

novaembed
easypin

