#!/bin/sh
. ./SourceMe
cd ../Kernel/${1}
make -j32 zImage
[ ! "$?" = "0" ] && return 1
make -j32 modules
[ ! "$?" = "0" ] && return 1
make imx6ul-14x14-evk.dtb
[ ! "$?" = "0" ] && return 1
make imx6q-novasomS.dtb
[ ! "$?" = "0" ] && return 1
make imx6sdl-novasomP_hdmi.dtb
[ ! "$?" = "0" ] && return 1
make imx6sdl-novasomP_lvds.dtb
[ ! "$?" = "0" ] && return 1
make imx6q-novasomP_hdmi.dtb
[ ! "$?" = "0" ] && return 1
#make imx6q-novasomP_lvds.dtb
#[ ! "$?" = "0" ] && return 1
return 0
