#!/bin/sh
. ./SourceMe
cd ../Kernel/${1}
make -j32 zImage
[ ! "$?" = "0" ] && return 1
make -j32 modules
[ ! "$?" = "0" ] && return 1
make imx6ul-14x14-evk.dtb
[ ! "$?" = "0" ] && return 1
make imx6q-novasomS.dtb
[ ! "$?" = "0" ] && return 1
###################### NOVAsomP ###############################
make imx6sdl-novasomP_hdmi_1280x720.dtb
[ ! "$?" = "0" ] && return 1
make imx6sdl-novasomP_hdmi_1920x1080.dtb
[ ! "$?" = "0" ] && return 1
make imx6sdl-novasomP_lvds_800x480.dtb
[ ! "$?" = "0" ] && return 1
return 0
