#!/bin/sh
. ./SourceMe
cd ../Kernel/${1}
make mrproper
make imx_novasoms_defconfig
[ ! "$?" = "0" ] && return 1
make -j32 zImage
[ ! "$?" = "0" ] && return 1
make -j32 modules
[ ! "$?" = "0" ] && return 1
return 0
