#!/bin/sh
DIRS="Bootloader/u-boot-novasom-2015.04 Kernel/linux-imx_3.10.53_1.1.0_ga Kernel/linux-imx_4.1.15_1.2.0_ga Doc Utils Qt/NOVAembed/NOVAembed"
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
echo "		Check for modified files"
for i in ${DIRS}; do
        cd /Devel/NOVAsom_SDK/$i
        BASE=`basename $i`
	RESULT=`git status | grep modified`
	if [ "$?" = "0" ]; then
		echo "${RED}-----> ${BASE} has files modified <-----${NC}"
	else
		echo "${GREEN}${BASE} is in sync${NC}"
	fi
done
