#!/bin/sh
PREPEND_PATH="/Devel/NOVAsom_SDK"
DIRS="Bootloader/u-boot-novasom-2015.04 Kernel/linux-imx_3.10.53_1.1.0_ga Kernel/linux-imx_4.1.15_1.2.0_ga Doc Utils Qt/NOVAembed/NOVAembed CodeBlocks"
REPOCOUNT=`echo "$DIRS" | awk '{print NF}'`
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo "****************************************"
echo "**  Check for locally modified files  **"
echo "****************************************"
echo ""
HERE=`pwd`
COUNTMODS=0
COUNTSENT=0
INCREMENT=1
for i in ${DIRS}; do
        cd /Devel/NOVAsom_SDK/$i
        BASE=`basename $i`
	RESULT=`git status | grep modified`
	if [ "$?" = "0" ]; then
		COUNTMODS=`expr $COUNTMODS + $INCREMENT`;
		echo -e "${RED}-----> ${BASE} has files modified <-----${NC}"
		echo -n "Do you want to send changes to git repo [Y/n] ? "
		read REPLY
		if [ "${REPLY}" = "Y" ]; then
			echo -n "Enter the text of the modification : "
			read TEXTMOD
			cd ${PREPEND_PATH}/${i}
			gitupdate "${TEXTMOD}"
			cd ${HERE} 
			COUNTSENT=`expr $COUNTSENT + $INCREMENT`;
		fi
	else
		echo -e "${GREEN}SYNC OK${NC} : ${BASE}"
	fi
done
echo ""
echo "Finished. Found ${COUNTMODS} modification(s) and ${COUNTSENT} updated repo(s) on ${REPOCOUNT} local repos"
echo ""
