#!/bin/bash
# ${1} pointer to the application_storage folder
# ${2} is the device
DISK=${2}


sync
rm -rf tmpmount
mkdir tmpmount
sleep 1
sudo mount ${DISK}3 tmpmount
[ "$?" != "0" ] && return 1
sudo rm -rf tmpmount/application_storage
sudo mkdir tmpmount/application_storage
echo -n "Copying application_storage ..."
sudo cp ${1}/* tmpmount/application_storage/.
echo "Done"
sudo umount tmpmount
sync

exit 0
