#!/bin/bash
. ./flash_functions
KERNEL="linux-imx_4.1.15_1.2.0_ga"
DTB_K_PATH="/Devel/NOVAsom_SDK/Kernel/${KERNEL}/arch/arm/boot/dts"
DTB_U_PATH="/Devel/NOVAsom_SDK/DtbUserWorkArea"

# ${1} is number of user partition
# ${2} is size of first user partition, if enabled
# ${3} is size of second user partition, if enabled
# ${4} is the device
# ${5} is the board name
# ${6} is the dtb for sdl
# ${7} is the dtb for quad
# ${8} if present and contains "user" then the dtbs are from user area

NUMBER_OF_USR_PARTTIONS=${1}
SIZE_OF_FIRST_PARTTION=${2}
SIZE_OF_2ND_PARTTION=${3}
DISK=${4}
BOARD_NAME=${5}

if [ "$8" = "user" ]; then
	DTB_FILESDL=${DTB_U_PATH}/${6}
	DTB_FILEQ=${DTB_U_PATH}/${7}
else
	DTB_FILESDL=${DTB_K_PATH}/${6}
	DTB_FILEQ=${DTB_K_PATH}/${7}
fi

[ "${1}" = "" ] && NUMBER_OF_USR_PARTTIONS="-" # Defaults to no user partitions
[ "${2}" = "" ] && SIZE_OF_FIRST_PARTTION="16"
[ "${3}" = "" ] && SIZE_OF_2ND_PARTTION="16"
[ "${4}" = "" ] && DISK="/dev/sdb"
[ "${5}" = "" ] && BOARD_NAME="NOVAsomP" # Defaults to P
[ "${6}" = "" ] && DTB_FILESDL="${DTB_K_PATH}/imx6sdl-novasomP.dtb" # Defaults to P HDMI
[ "${7}" = "" ] && DTB_FILEQ="${DTB_K_PATH}/imx6q-novasomP.dtb" # Defaults to P HDMI

echo "#####################"
echo "####   init_usd  ####"
echo "#####################"
if [ "$BOARD_NAME" = "NOVAsomU" ]; then 
	Uinit_usd $NUMBER_OF_USR_PARTTIONS $SIZE_OF_FIRST_PARTTION $SIZE_OF_2ND_PARTTION $DISK $BOARD_NAME
else
	init_usd $NUMBER_OF_USR_PARTTIONS $SIZE_OF_FIRST_PARTTION $SIZE_OF_2ND_PARTTION $DISK $BOARD_NAME
fi
if ! [ "$?" = "0" ]; then
        echo "init_usd error"
        exit 1
fi
echo "#####################"
echo "####  format_usd ####"
echo "#####################"
format_usd $NUMBER_OF_USR_PARTTIONS $DISK
if ! [ "$?" = "0" ]; then
        echo "format_usd error"
        exit 1
fi
echo "#####################"
echo "####  store_bin  ####"
echo "#####################"
if [ "${BOARD_NAME}" = "NOVAsomU" ]; then
	Ustore_bin $DISK $BOARD_NAME
else
	store_bin $DISK $BOARD_NAME $DTB_FILESDL $DTB_FILEQ
fi
if ! [ "$?" = "0" ]; then
        echo "store_bin error"
        exit 1
fi
exit 0
