#!/bin/sh
[ "$1" = "" ] && echo "No input file given"
[ "$1" = "" ] && return 1
[ ! "$2" = "P" ] && echo "Not implemented yet"
[ ! "$2" = "P" ] && return 1
INFILE=$1
DTS_INFILE=${INFILE}.dts
DTS_TMP=${INFILE}.tmp.dts
DTB_OUTFILE=${INFILE}.dtb
DTC_EXEC="/Devel/NOVAsom_SDK/Kernel/linux-imx_4.1.15_1.2.0_ga/scripts/dtc/dtc"
WORKAREA_LOCATION="/Devel/NOVAsom_SDK/DtbUserWorkArea"
KERNEL_LOCATION="/Devel/NOVAsom_SDK/Kernel/linux-imx_4.1.15_1.2.0_ga/arch/arm/boot/dts"

[ ! -d ${WORKAREA_LOCATION} ] && mkdir ${WORKAREA_LOCATION}
[ ! -f ${WORKAREA_LOCATION}/${DTS_INFILE} ] && echo "File not found"
[ ! -f ${WORKAREA_LOCATION}/${DTS_INFILE} ] && return 1
STD_FILES="imx6dl.dtsi  imx6dl-pinfunc.h  imx6qdl.dtsi  skeleton.dtsi"
for i in ${STD_FILES}; do
	[ -f ${WORKAREA_LOCATION}/${i} ] && rm ${WORKAREA_LOCATION}/${i}
	cp ${KERNEL_LOCATION}/${i} ${WORKAREA_LOCATION}/.
done
cd ${WORKAREA_LOCATION}
cpp -nostdinc -I ${KERNEL_LOCATION}/include -undef -x assembler-with-cpp ${DTS_INFILE} > ${DTS_TMP}
[ ! "$?" = "0" ] && return 1
${DTC_EXEC} -O dtb -b 0 -o ${DTB_OUTFILE} ${DTS_TMP}
rm ${INFILE}.tmp.dts
[ ! "$?" = "0" ] && return 1
return 0
